#!/bin/bash
##########################################
# Part 3        : Bridge Configuration
# Description   : Setup your Bridge Relay
##########################################

# define colors
clear='\033[0m'
blue='\033[1;34m'
purple='\033[1;35m'
green='\033[0;32m'
red='\033[0;31m'

############################################################
# Bridge Installation and Setup                            #
############################################################


# Install obfs4proxy
printf "${purple}\n[+] Installing obfs4proxy ... ${clear}\n"
sudo apt install -t bullseye-backports obfs4proxy

# Edit the config for the Bridge file
printf "\n${blue}[~] Configuring Bridge file ...${clear}\n"
cat > /etc/tor/torrc << EOL

BridgeRelay 1

# Replace "TODO1" with a Tor port of your choice.
# This port must be externally reachable.
# Avoid port 9001 because it's commonly associated with Tor and censors may be scanning the Internet for this port.
ORPort TODO1

ServerTransportPlugin obfs4 exec /usr/bin/obfs4proxy

# Replace "TODO2" with an obfs4 port of your choice.
# This port must be externally reachable and must be different from the one specified for ORPort.
# Avoid port 9001 because it's commonly associated with Tor and censors may be scanning the Internet for this port.
ServerTransportListenAddr obfs4 0.0.0.0:TODO2

# Local communication port between Tor and obfs4.  Always set this to "auto".
# "Ext" means "extended", not "external".  Don't try to set a specific port number, nor listen on 0.0.0.0.
ExtORPort auto

# Replace "<address@email.com>" with your email address so we can contact you if there are problems with your bridge.
# This is optional but encouraged.
ContactInfo <address@email.com>

# Pick a nickname that you like for your bridge.  This is optional.
Nickname PickANickname
